name: SglPPow
version: 2.0
date: 2016-08-11
description: |
    Database of groups of prime-power order for some prime-powers

authors:
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

maintainers:
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

GAP: "4.5.3"

suggested-pkgs:
    - name: "LiePRing"
      version: ">=1.8"
      url: "https://gap-packages.github.io/liepring/"
    - name: "LieRing"
      version: ">=2.2"
      url: "http://www.science.unitn.it/~degraaf/liering.html"

www: http://www.icm.tu-bs.de/~beick/soft/sglppow/
readme: README
packageinfo: http://www.icm.tu-bs.de/~beick/soft/sglppow/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.icm.tu-bs.de/~beick/soft/sglppow/sglppow-2.0.tar.gz

abstract: |

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
